
#- name: Adding Mongodb repo
#  shell: echo"[mongodb-org-4.4]\n
#  name=MongoDB Repository\n
#  baseurl=https://repo.mongodb.org/yum/amazon/2/mongodb-org/4.4/x86_64/\n
#  gpgcheck=1\n
#  enabled=1\n
#  gpgkey=https://www.mongodb.org/static/pgp/server-4.4.asc" >/etc/yum.repos.d/mongodb-org-4.4.repo

- name: Adding repo
  yum_repository:
    name: mongodb-org-4.4
    description: MongoDB Repository
    baseurl: https://repo.mongodb.org/yum/amazon/2/mongodb-org/4.4/x86_64/
    file: mongodb-org-4.4
    gpgcheck: yes
    enabled: yes
    gpgkey: https://www.mongodb.org/static/pgp/server-4.4.asc

- name: Install MongoDB
  yum:
    name: mongodb-org
    state: installed

- name: Start MongoDB service
  systemd:
    name: mongod
    enabled: yes
    state: started


- name: reload daemon mongodb
  systemd:
    name: mongod
    daemon_reload: yes


- name: Install Docker
  shell: amazon-linux-extras install docker -y
  become: yes

- name: Stating Docker service
  systemd:
    name: docker
    state: started

- name: create directory for docker
  file:
    path: /home/ec2-user/docker
    state: directory
    owner: ec2-user
    group: docker

- name: adding user  to group sudo
  user:
    name: ec2-user
    groups: docker
    append: yes
  become: yes

- name: reloading the daemon
  systemd:
    name: docker
    state: restarted
    daemon_reload: yes

- name: copy Dockerfile
  copy:
    src: ./Dockerfile
    dest: /home/ec2-user/docker/Dockerfile
    owner: ec2-user
    group: docker


- name: build container image
  docker_image:
    name: tomcat:8.0-alpine
    build:
      path: /home/ec2-user/docker
      source: build
    state: present


#- name: Build image and with buildargs
#  docker_image:
#    path: /path/to/build/dir
#    name: myimage
#    buildargs:
#      log_volume: /var/log/myapp
#      listen_port: 8080