- name: installing tomcat server
  yum:
    name:
      - tomcat
      - tomcat-webapps

    state: absent

#- name: starting tomcat server
#  systemd:
#    name: tomcat
#    state: started
#    enabled: yes
