- name: removing old contents
  file:
    path: /usr/share/nginx/html
    state: absent

- name: setting up nginx
  shell: amazon-linux-extras install nginx1 -y

- name: starting the server
  systemd:
    name: nginx.service
    state: started

- name: copying html docs
  copy:
    src: