#- name: removing old contents
#  file:
#    path: /usr/share/nginx/html
#    state: absent
- name: removing
  shell: yum remove nginx -y

- name: setting up nginx
  shell: amazon-linux-extras install nginx1 -y

- name: starting the server
  systemd:
    name: nginx.service
    state: started

- name: copying html docs
  shell: curl -s -L -o /tmp/html "https://gist.github.com/b55828fa05ed3470d352.git"
#  git:
#    repo: https://gist.github.com/b55828fa05ed3470d352.git
#    dest: /tmp/html

