- name: Adding mongoDB repositories
  yum_repository:
    name: MongoDB Repository
    description: mongodb repo
    baseurl: https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/4.2/x86_64/
    file: /etc/yum.repos.d/mongodb.repo
    gpgcheck: yes
    enabled: yes
    gpgkey: https://www.mongodb.org/static/pgp/server-4.2.asc



- name: Install MongoDB
  yum:
    name: mongodb-org
    state: present

- name: Start MongoDB service
  systemd:
    name: mongod
    enabled: yes
    state: started


- name: restarted mongodb
  systemd:
    name: mongod
    state: restarted



