- name: Adding mongoDB repositories
  yum_repository:
    name: MongoDB
    description: EPEL YUM repo
    baseurl: https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/4.2/x86_64/
    gpgcheck: yes
    enabled: yes
    gpgkey: https://www.mongodb.org/static/pgp/server-4.2.asc
    file: mongodb


- name: Install MongoDB
  yum:
    name: mongodb-org
    state: present

- name: Update MongoDB Listen Address
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'


- name: Start MongoDB service
  systemd:
    name: mongod
    enabled: yes
    state: started


- name: restarted mongodb
  systemd:
    name: mongod
    state: restarted



