- name: installing tomcat server
  yum:
    name:
      - tomcat
      - tomcat-webapps

    state: present

- name: starting tomcat server
  systemd:
    name: tomcat
    state: started
    enabled: yes
